### ISSUE TITLE
How to extract the .egg file in DIML dataset?

### ISSUE THREAD

**Issue by marcelsan** [prs-eth/graph-super-resolution#1]
Hello, thanks for sharing the code.
I downloaded the DIML dataset., but I cannot open the .egg format file. How did you decompress this file format?
I tried the unzip command, but it didn't work

**Comment by alebeck** [comment]
Hi, did you download the indoor data sample? It consists of two files "indoor_train.zip" and "indoor_test.zip", and there should be no .egg files. Let me know in case you don't get it to work!

**Comment by marcelsan** [comment]
Ah, I actually downloaded the content from these folders: `https://drive.google.com/drive/folders/1OsuHBrtstN_lBhUHcpqqNEIo1rCUczYo?usp=sharing`

I thought this was the complete dataset and your approach needed all those images. So, only the sample data is sufficient?

**Comment by alebeck** [comment]
Exactly, we use the indoor sample subset for our project. All the images are contained within the "indoor_train.zip" and "indoor_test.zip" files.
