### ISSUE TITLE
Details want to discuss

### ISSUE THREAD

**Issue by jiayaozhang** [prs-eth/graph-super-resolution#4]
hi for the evaluation process

`python run_eval.py --checkpoint <...> --dataset <...> --data-dir <...>`

what is the difference between `--dataset` and `--data-dir`

and for example if I add --dataset DIML then what is for `data-dir` ? 

Many thanks!

**Comment by riccardodelutio** [comment]
Thanks for your interest in our work! 
The `--dataset` argument is used to select the name of the dataset to run the evaluation on, you can choose `DIML`, `Middlebury` or `NYUv2`. 
The `--data-dir` argument is used to define the path of the directory where your data is stored, ie: `./data`.
