### ISSUE TITLE
about the visualization

### ISSUE THREAD

**Issue by caijianghe** [prs-eth/graph-super-resolution#5]
Hello,dear author, I have some questions about visualization. for the residual plots, What should the [percentil](https://numpy.org/doc/stable/reference/generated/numpy.percentile.html) be set to for residual map visualization.So that I can achieve the same visual effects as presented in your paper. the following is my code.
vvmin = np.percentile(residual, 0.5, axis=(0, 1), keepdims=True)
vvmax = np.percentile(residual, 99.5, axis=(0, 1), keepdims=True)
if (-vvmin) > vvmax:
          vvmax = -vvmin
else:
          vvmin = -vvmax

**Comment by riccardodelutio** [comment]
Thank you for your interest in our work! I'm afraid I don't remember the exact setting we used for the visualization of our results. The settings were picked to ease visual comparison between results, importantly the same vmin/vmax settings should be used in all comparisons (all images/methods) to make the comparison valid.
