### ISSUE TITLE
Labeled Dataset cannot be downloaded

### ISSUE THREAD

**Issue by Sincedawn** [prs-eth/graph-super-resolution#6]

**Comment by riccardodelutio** [comment]
Hi there,

Thank you for your interest in our work! Would you mind providing a bit more information about your issue? The links to download the datasets seem to be functioning to me.

**Comment by Sincedawn** [comment]
When I click the link, it cannot be run.
[
![Uploading 屏幕截图 2024-01-10 124723.png…]()
](url)

**Comment by Sincedawn** [comment]
When I click it, it cannot be run
![屏幕截图 2024-01-10 124723](https://github.com/prs-eth/graph-super-resolution/assets/75066571/533abef8-6fa7-4dce-ab8e-33d477c0f444)
![屏幕截图 2024-01-10 124758](https://github.com/prs-eth/graph-super-resolution/assets/75066571/94404c8b-428f-469e-a4fd-b36170dee8ce)

**Comment by riccardodelutio** [comment]
Closing the issue as this issue stems from the NYUv2 website and has been fixed. Tested today, and I can download the dataset. Thanks!
