### ISSUE TITLE
Inquiry about the visualization

### ISSUE THREAD

**Issue by calvindiao** [prs-eth/graph-super-resolution#7]
Hi, Riccardo. 
Thanks very much for your work. I am a new beginner for CV, and I am really interested in super-resolution. However, I have some confusion in reproducing your work.
I have trained NYUv2 and All I could get are args.csv, best_model.pth, events.out.tfevents.1708975026.UbuntuOS.38019.0 and last_model.pth in "graph-super-resolution/output/NYUv2/experiment3" .

How could I get the beautiful picture displayed in your paper? They are just some binary files and py_evaluation just gives me some number. I know my question is a bit stupid, Sorry for bothering you. Could you give me some keywords or hints?
![image](https://github.com/prs-eth/graph-super-resolution/assets/50324758/353d6df9-a565-4846-8b4e-95028151403f)

**Comment by riccardodelutio** [comment]
Hi there, thank you for your interest in our work! Once you load the model, and make a prediction you can visualize the prediction [`y_pred`](https://github.com/prs-eth/graph-super-resolution/blob/master/model/graph_sr_net.py#L91) with any tool you prefer, one possibility is [imshow](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.imshow.html) with a suitable colormap.
